version: '2.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: password

  pms:
    image: tomcat
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./target/project-management-system.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/project-management-system:/usr/local/tomcat/webapps/ROOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
